apiVersion: v1
kind: Service
metadata:
  name: notes-app
spec:
  type: LoadBalancer
  loadBalancerIP: <STATIC_IP_HERE>
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: notes-app

